import type { DictionaryEntry } from "@/types";

const WORD_DATA: DictionaryEntry[] = [
  { word: "time", partOfSpeech: "noun", definition: "The indefinite continued progress of existence and events", examples: ["Time flies when you're having fun.", "I don't have time right now."], synonyms: ["moment", "period", "duration", "era"], antonyms: ["eternity", "instant"], etymology: "Old English 'tima'", relatedWords: ["clock", "hour", "schedule"], collocations: ["free time", "on time", "waste time", "time management"] },
  { word: "love", partOfSpeech: "noun", definition: "An intense feeling of deep affection and care", examples: ["Love conquers all.", "Their love grew stronger every day."], synonyms: ["affection", "devotion", "adoration", "fondness"], antonyms: ["hate", "dislike", "apathy"], etymology: "Old English 'lufu'", relatedWords: ["heart", "romance", "passion"], collocations: ["fall in love", "love at first sight", "true love"] },
  { word: "knowledge", partOfSpeech: "noun", definition: "Facts, information, and skills acquired through experience or education", examples: ["Knowledge is power.", "She has extensive knowledge of history."], synonyms: ["wisdom", "understanding", "expertise", "learning"], antonyms: ["ignorance", "foolishness"], etymology: "Old English 'cnawan'", relatedWords: ["information", "education", "insight"], collocations: ["common knowledge", "to my knowledge", "knowledge base"] },
  { word: "freedom", partOfSpeech: "noun", definition: "The power or right to act, speak, or think as one wants", examples: ["Freedom is a fundamental human right.", "Birds represent freedom."], synonyms: ["liberty", "independence", "autonomy"], antonyms: ["slavery", "captivity", "oppression"], etymology: "Old English 'freodom'", relatedWords: ["rights", "democracy", "emancipation"], collocations: ["freedom of speech", "fight for freedom", "personal freedom"] },
  { word: "truth", partOfSpeech: "noun", definition: "The quality or state of being in accordance with fact or reality", examples: ["Tell me the truth.", "The truth will set you free."], synonyms: ["fact", "reality", "honesty", "verity"], antonyms: ["lie", "falsehood", "deception"], etymology: "Old English 'triewth'", relatedWords: ["honesty", "fact", "reality"], collocations: ["tell the truth", "truth be told", "in truth"] },
  { word: "hope", partOfSpeech: "noun", definition: "A feeling of expectation and desire for a certain thing to happen", examples: ["Don't lose hope.", "There is always hope."], synonyms: ["optimism", "expectation", "faith", "aspiration"], antonyms: ["despair", "hopelessness"], etymology: "Old English 'hopa'", relatedWords: ["dream", "wish", "belief"], collocations: ["give up hope", "hope for the best", "high hopes"] },
  { word: "dream", partOfSpeech: "noun", definition: "A series of thoughts, images, and sensations occurring in a person's mind during sleep; or a cherished aspiration", examples: ["Follow your dreams.", "I had a strange dream last night."], synonyms: ["vision", "ambition", "aspiration", "fantasy"], antonyms: ["reality", "nightmare"], etymology: "Old English 'dream'", relatedWords: ["sleep", "vision", "goal"], collocations: ["dream come true", "have a dream", "pipe dream"] },
  { word: "peace", partOfSpeech: "noun", definition: "Freedom from disturbance; tranquility and harmony", examples: ["World peace is a noble goal.", "I need some peace and quiet."], synonyms: ["tranquility", "harmony", "calm", "serenity"], antonyms: ["war", "conflict", "chaos"], etymology: "Latin 'pax'", relatedWords: ["calm", "harmony", "stillness"], collocations: ["at peace", "peace of mind", "make peace"] },
  { word: "energy", partOfSpeech: "noun", definition: "The strength and vitality required for sustained activity; power derived from physical or chemical resources", examples: ["I have so much energy today.", "Solar energy is renewable."], synonyms: ["vigor", "force", "power", "vitality"], antonyms: ["lethargy", "weakness", "fatigue"], etymology: "Greek 'energeia'", relatedWords: ["power", "strength", "force"], collocations: ["solar energy", "full of energy", "energy source"] },
  { word: "music", partOfSpeech: "noun", definition: "Vocal or instrumental sounds combined to produce beauty of form, harmony, and expression of emotion", examples: ["Music is the universal language.", "I love listening to classical music."], synonyms: ["melody", "harmony", "song", "tune"], antonyms: ["silence", "noise"], etymology: "Greek 'mousike'", relatedWords: ["song", "rhythm", "melody"], collocations: ["listen to music", "play music", "live music"] },
  { word: "serendipity", partOfSpeech: "noun", definition: "The occurrence of events by chance in a happy or beneficial way", examples: ["Finding this cafe was pure serendipity.", "Their meeting was a moment of serendipity."], synonyms: ["chance", "fortune", "luck", "destiny"], antonyms: ["misfortune", "bad luck"], etymology: "Coined by Horace Walpole, 1754, from Persian fairy tale", relatedWords: ["coincidence", "fate"], collocations: ["pure serendipity", "moment of serendipity", "happy serendipity"] },
  { word: "ephemeral", partOfSpeech: "adjective", definition: "Lasting for a very short time; transient", examples: ["Fame can be ephemeral.", "The beauty of cherry blossoms is ephemeral."], synonyms: ["transient", "fleeting", "momentary", "short-lived"], antonyms: ["eternal", "permanent", "everlasting"], etymology: "Greek 'ephemeros' meaning 'lasting only one day'", relatedWords: ["temporary", "passing", "brief"], collocations: ["ephemeral nature", "ephemeral beauty", "ephemeral moment"] },
  { word: "euphoria", partOfSpeech: "noun", definition: "A feeling or state of intense excitement and happiness", examples: ["Winning the championship brought pure euphoria.", "She felt a wave of euphoria."], synonyms: ["elation", "ecstasy", "bliss", "joy"], antonyms: ["despair", "misery", "depression"], etymology: "Greek 'euphoria' meaning 'well-bearing'", relatedWords: ["happiness", "bliss", "delight"], collocations: ["state of euphoria", "pure euphoria", "wave of euphoria"] },
  { word: "melancholy", partOfSpeech: "noun", definition: "A deep, persistent sadness; pensive sadness with no obvious cause", examples: ["Autumn always brings a touch of melancholy.", "A sense of melancholy filled the room."], synonyms: ["sadness", "gloom", "sorrow", "wistfulness"], antonyms: ["joy", "happiness", "cheerfulness"], etymology: "Greek 'melankholia' meaning 'black bile'", relatedWords: ["nostalgia", "sadness", "grief"], collocations: ["deep melancholy", "sweet melancholy", "sense of melancholy"] },
  { word: "ecstatic", partOfSpeech: "adjective", definition: "Feeling or expressing overwhelming happiness or joyful excitement", examples: ["The fans were ecstatic when their team won.", "She was ecstatic about the news."], synonyms: ["elated", "euphoric", "overjoyed", "thrilled"], antonyms: ["miserable", "depressed", "devastated"], etymology: "Greek 'ekstatikos' meaning 'unstable, displaced'", relatedWords: ["joyful", "euphoric", "blissful"], collocations: ["absolutely ecstatic", "ecstatic about", "ecstatic joy"] },
  { word: "compassion", partOfSpeech: "noun", definition: "Sympathetic pity and concern for the sufferings or misfortunes of others", examples: ["Show compassion to those in need.", "Her compassion knows no bounds."], synonyms: ["empathy", "sympathy", "kindness", "humanity"], antonyms: ["cruelty", "indifference", "apathy"], etymology: "Latin 'compassio' meaning 'to suffer with'", relatedWords: ["empathy", "kindness", "care"], collocations: ["show compassion", "feel compassion", "act of compassion"] },
  { word: "gratitude", partOfSpeech: "noun", definition: "The quality of being thankful; readiness to show appreciation", examples: ["Express your gratitude often.", "I feel deep gratitude for your help."], synonyms: ["thankfulness", "appreciation", "recognition"], antonyms: ["ingratitude", "ungratefulness"], etymology: "Latin 'gratitudo' from 'gratus' meaning 'thankful'", relatedWords: ["thanks", "appreciation", "gratefulness"], collocations: ["deep gratitude", "express gratitude", "attitude of gratitude"] },
  { word: "nostalgia", partOfSpeech: "noun", definition: "A sentimental longing for the past, typically for a period or place with happy personal associations", examples: ["Looking at old photos filled her with nostalgia.", "The song evokes a sense of nostalgia."], synonyms: ["longing", "wistfulness", "reminiscence", "yearning"], antonyms: [], etymology: "Greek 'nostos' (return home) + 'algos' (pain)", relatedWords: ["memory", "longing", "sentiment"], collocations: ["sense of nostalgia", "wave of nostalgia", "nostalgia for"] },
  { word: "serenity", partOfSpeech: "noun", definition: "The state of being calm, peaceful, and untroubled", examples: ["The serenity of the lake was calming.", "She radiated serenity."], synonyms: ["tranquility", "peace", "calm", "stillness"], antonyms: ["chaos", "turmoil", "agitation"], etymology: "Latin 'serenus' meaning 'clear, calm'", relatedWords: ["peace", "calm", "tranquility"], collocations: ["inner serenity", "perfect serenity", "serenity now"] },
  { word: "anguish", partOfSpeech: "noun", definition: "Severe mental or physical pain or suffering", examples: ["She cried out in anguish.", "The decision caused him great anguish."], synonyms: ["agony", "torment", "distress", "suffering"], antonyms: ["comfort", "relief", "peace"], etymology: "Latin 'angustia' meaning 'tightness, straitness'", relatedWords: ["pain", "suffering", "torment"], collocations: ["mental anguish", "in anguish", "cry of anguish"] },
  { word: "wanderlust", partOfSpeech: "noun", definition: "A strong desire to travel and explore the world", examples: ["Her wanderlust took her to over 50 countries.", "I have a serious case of wanderlust."], synonyms: ["travel bug", "restlessness", "itchy feet"], antonyms: ["homebody", "stability"], etymology: "German 'Wanderlust' from 'wandern' (to hike) + 'Lust' (desire)", relatedWords: ["travel", "adventure", "exploration"], collocations: ["have wanderlust", "satisfy wanderlust", "wanderlust spirit"] },
  { word: "magnificent", partOfSpeech: "adjective", definition: "Extremely beautiful, elaborate, or impressive; splendid", examples: ["The palace was absolutely magnificent.", "A magnificent view of the mountains."], synonyms: ["splendid", "grand", "impressive", "gorgeous"], antonyms: ["ordinary", "modest", "unimpressive"], etymology: "Latin 'magnificus' meaning 'great, splendid'", relatedWords: ["grand", "splendid", "superb"], collocations: ["absolutely magnificent", "magnificent view", "magnificent achievement"] },
  { word: "ethereal", partOfSpeech: "adjective", definition: "Extremely delicate and light in a way that seems too perfect for this world", examples: ["An ethereal beauty.", "The music had an ethereal quality."], synonyms: ["delicate", "heavenly", "airy", "celestial"], antonyms: ["earthly", "heavy", "mundane"], etymology: "Greek 'aither' meaning 'upper air, sky'", relatedWords: ["delicate", "divine", "otherworldly"], collocations: ["ethereal beauty", "ethereal quality", "ethereal light"] },
  { word: "luminous", partOfSpeech: "adjective", definition: "Full of or shedding light; bright or shining, especially in the dark", examples: ["Luminous stars filled the night sky.", "Her smile was luminous."], synonyms: ["radiant", "glowing", "brilliant", "shining"], antonyms: ["dark", "dim", "dull"], etymology: "Latin 'luminosus' from 'lumen' meaning 'light'", relatedWords: ["radiant", "bright", "glowing"], collocations: ["luminous glow", "luminous stars", "luminous beauty"] },
  { word: "vibrant", partOfSpeech: "adjective", definition: "Full of energy and life; bright and striking", examples: ["A vibrant city full of culture.", "The painting used vibrant colors."], synonyms: ["lively", "dynamic", "colorful", "vivid"], antonyms: ["dull", "lifeless", "pale", "bland"], etymology: "Latin 'vibrare' meaning 'to shake, agitate'", relatedWords: ["lively", "colorful", "energetic"], collocations: ["vibrant colors", "vibrant city", "vibrant personality"] },
  { word: "resplendent", partOfSpeech: "adjective", definition: "Attractive and impressive through being richly colorful or sumptuous", examples: ["She looked resplendent in her evening gown.", "The hall was resplendent with decorations."], synonyms: ["splendid", "glorious", "magnificent", "dazzling"], antonyms: ["dull", "drab", "plain"], etymology: "Latin 'resplendere' meaning 'to shine back'", relatedWords: ["glorious", "splendid", "radiant"], collocations: ["resplendent in", "resplendent with", "absolutely resplendent"] },
  { word: "effervescent", partOfSpeech: "adjective", definition: "Vivacious and enthusiastic; bubbling with excitement", examples: ["Her effervescent personality lit up the room.", "An effervescent sense of joy."], synonyms: ["bubbly", "lively", "enthusiastic", "sparkling"], antonyms: ["dull", "flat", "lifeless"], etymology: "Latin 'effervescere' meaning 'to boil up'", relatedWords: ["bubbly", "lively", "sparkling"], collocations: ["effervescent personality", "effervescent charm", "effervescent spirit"] },
  { word: "mellifluous", partOfSpeech: "adjective", definition: "Of a voice or words sweet or musical; pleasant to hear", examples: ["Her mellifluous voice calmed everyone.", "A mellifluous stream of words."], synonyms: ["sweet-sounding", "melodious", "dulcet", "honeyed"], antonyms: ["harsh", "grating", "cacophonous"], etymology: "Latin 'mel' (honey) + 'fluere' (to flow)", relatedWords: ["melodious", "musical", "sweet"], collocations: ["mellifluous voice", "mellifluous tones", "mellifluous speech"] },
  { word: "kaleidoscopic", partOfSpeech: "adjective", definition: "Having complex patterns of colors; rapidly changing or shifting", examples: ["Kaleidoscopic patterns filled the screen.", "The city offers a kaleidoscopic mix of cultures."], synonyms: ["multicolored", "varied", "changing", "myriad"], antonyms: ["monotonous", "uniform", "static"], etymology: "Greek 'kalos' (beautiful) + 'eidos' (form) + 'skopein' (to view)", relatedWords: ["colorful", "varied", "diverse"], collocations: ["kaleidoscopic patterns", "kaleidoscopic array", "kaleidoscopic colors"] },
  { word: "quintessential", partOfSpeech: "adjective", definition: "Representing the most perfect or typical example of a quality or class", examples: ["He's the quintessential gentleman.", "A quintessential example of Renaissance art."], synonyms: ["typical", "archetypal", "ideal", "classic"], antonyms: ["atypical", "unusual", "unrepresentative"], etymology: "Latin 'quinta essentia' meaning 'fifth essence'", relatedWords: ["classic", "ideal", "perfect"], collocations: ["quintessential example", "quintessential representation", "the quintessential"] },
  { word: "ineffable", partOfSpeech: "adjective", definition: "Too great or extreme to be expressed or described in words", examples: ["The beauty was ineffable.", "An ineffable sense of peace washed over her."], synonyms: ["indescribable", "inexpressible", "beyond words", "unutterable"], antonyms: ["describable", "expressible"], etymology: "Latin 'ineffabilis' from 'in-' (not) + 'effari' (to speak out)", relatedWords: ["indescribable", "transcendent", "unspeakable"], collocations: ["ineffable beauty", "ineffable joy", "ineffable sadness"] },
  { word: "paradigm", partOfSpeech: "noun", definition: "A typical example or pattern of something; a model or worldview", examples: ["A new paradigm in computing.", "The paradigm has shifted."], synonyms: ["model", "pattern", "framework", "worldview"], antonyms: ["anomaly", "exception"], etymology: "Greek 'paradeigma' meaning 'pattern, example'", relatedWords: ["model", "framework", "standard"], collocations: ["paradigm shift", "new paradigm", "dominant paradigm"] },
  { word: "dichotomy", partOfSpeech: "noun", definition: "A division or contrast between two things that are represented as being opposed or entirely different", examples: ["The dichotomy between good and evil.", "There's a false dichotomy in that argument."], synonyms: ["division", "contrast", "duality", "polarity"], antonyms: ["unity", "similarity", "harmony"], etymology: "Greek 'dikhotomia' from 'dikha' (in two) + 'temnein' (to cut)", relatedWords: ["contrast", "division", "polarity"], collocations: ["false dichotomy", "sharp dichotomy", "dichotomy between"] },
  { word: "juxtaposition", partOfSpeech: "noun", definition: "The fact of two things being seen or placed close together with contrasting effect", examples: ["The juxtaposition of old and new architecture.", "A striking juxtaposition of colors."], synonyms: ["contrast", "comparison", "proximity", "collocation"], antonyms: ["separation", "isolation"], etymology: "Latin 'juxta' (near) + 'positio' (placement)", relatedWords: ["contrast", "comparison", "pairing"], collocations: ["striking juxtaposition", "juxtaposition of", "interesting juxtaposition"] },
  { word: "nuance", partOfSpeech: "noun", definition: "A subtle difference in or shade of meaning, expression, or sound", examples: ["Understanding cultural nuances is important.", "Every nuance of her performance was perfect."], synonyms: ["subtlety", "shade", "distinction", "gradation"], antonyms: ["obviousness", "clarity", "uniformity"], etymology: "French from 'nuer' meaning 'to shade, to show slight variations'", relatedWords: ["subtlety", "distinction", "refinement"], collocations: ["subtle nuance", "cultural nuance", "nuance of meaning"] },
  { word: "pragmatic", partOfSpeech: "adjective", definition: "Dealing with things sensibly and practically rather than theoretically", examples: ["Take a pragmatic approach to the problem.", "She's known for her pragmatic solutions."], synonyms: ["practical", "realistic", "sensible", "utilitarian"], antonyms: ["idealistic", "impractical", "theoretical"], etymology: "Greek 'pragmatikos' from 'pragma' (deed, act)", relatedWords: ["practical", "realistic", "sensible"], collocations: ["pragmatic approach", "pragmatic solution", "pragmatic person"] },
  { word: "ubiquitous", partOfSpeech: "adjective", definition: "Present, appearing, or found everywhere", examples: ["Smartphones are ubiquitous now.", "His influence is ubiquitous in the industry."], synonyms: ["omnipresent", "pervasive", "universal", "ever-present"], antonyms: ["rare", "scarce", "uncommon"], etymology: "Latin 'ubique' meaning 'everywhere'", relatedWords: ["universal", "pervasive", "common"], collocations: ["ubiquitous presence", "seemingly ubiquitous", "ubiquitous nature"] },
  { word: "metaphysical", partOfSpeech: "adjective", definition: "Concerned with abstract thought or subjects like existence, causality, or the nature of reality", examples: ["Metaphysical questions about reality.", "The poem has metaphysical qualities."], synonyms: ["abstract", "philosophical", "transcendental", "theoretical"], antonyms: ["physical", "concrete", "material"], etymology: "Greek 'meta' (beyond) + 'phusika' (physical)", relatedWords: ["philosophical", "abstract", "spiritual"], collocations: ["metaphysical question", "metaphysical poetry", "metaphysical realm"] },
  { word: "paradox", partOfSpeech: "noun", definition: "A seemingly absurd or self-contradictory statement that may actually be true", examples: ["It's a paradox that standing is more tiring than walking.", "The paradox of choice."], synonyms: ["contradiction", "enigma", "puzzle", "anomaly"], antonyms: ["certainty", "consistency"], etymology: "Greek 'paradoxon' from 'para-' (beyond) + 'doxa' (opinion)", relatedWords: ["contradiction", "enigma", "mystery"], collocations: ["apparent paradox", "paradox of", "resolve a paradox"] },
  { word: "zeitgeist", partOfSpeech: "noun", definition: "The defining spirit or mood of a particular period of history as shown by the ideas and beliefs of the time", examples: ["The novel captures the zeitgeist of the 1960s.", "Tech startups embody the modern zeitgeist."], synonyms: ["spirit of the age", "mood", "atmosphere", "ethos"], antonyms: [], etymology: "German 'Zeit' (time) + 'Geist' (spirit)", relatedWords: ["ethos", "mood", "climate"], collocations: ["capture the zeitgeist", "embody the zeitgeist", "the zeitgeist of"] },
  { word: "epiphany", partOfSpeech: "noun", definition: "A moment of sudden revelation or insight; a profound realization", examples: ["I had an epiphany about my career path.", "The epiphany struck her during the walk."], synonyms: ["revelation", "insight", "realization", "awakening"], antonyms: ["confusion", "misunderstanding"], etymology: "Greek 'epiphaneia' meaning 'manifestation, appearance'", relatedWords: ["revelation", "insight", "awakening"], collocations: ["have an epiphany", "sudden epiphany", "profound epiphany"] },
  { word: "algorithm", partOfSpeech: "noun", definition: "A process or set of rules to be followed in calculations or problem-solving operations", examples: ["The algorithm sorts data efficiently.", "Machine learning uses complex algorithms."], synonyms: ["procedure", "method", "formula", "process"], antonyms: [], etymology: "From al-Khwarizmi, Persian mathematician", relatedWords: ["program", "code", "logic"], collocations: ["sorting algorithm", "algorithm design", "machine learning algorithm"] },
  { word: "binary", partOfSpeech: "adjective", definition: "Relating to, composed of, or involving two things; using a system of numerical notation with 2 as its base", examples: ["Computers use binary code.", "Binary means having two options."], synonyms: ["dual", "double", "twofold", "base-2"], antonyms: ["analog", "decimal", "continuous"], etymology: "Latin 'binarius' from 'bini' meaning 'two together'", relatedWords: ["digital", "Boolean", "bit"], collocations: ["binary code", "binary system", "binary number", "binary choice"] },
  { word: "neural", partOfSpeech: "adjective", definition: "Relating to a nerve or the nervous system; relating to a neural network in computing", examples: ["Neural networks mimic the brain.", "Neural pathways process information."], synonyms: ["cognitive", "synaptic", "nervous"], antonyms: [], etymology: "Greek 'neuron' meaning 'nerve, sinew'", relatedWords: ["cognitive", "synaptic", "brain"], collocations: ["neural network", "neural pathway", "neural processing"] },
  { word: "entropy", partOfSpeech: "noun", definition: "A measure of disorder or randomness in a system; lack of order or predictability", examples: ["Entropy increases over time in closed systems.", "The entropy of the universe tends to a maximum."], synonyms: ["disorder", "chaos", "randomness", "decay"], antonyms: ["order", "organization"], etymology: "Greek 'entropia' meaning 'a turning toward'", relatedWords: ["chaos", "disorder", "decay"], collocations: ["high entropy", "entropy increase", "information entropy"] },
  { word: "heuristic", partOfSpeech: "adjective", definition: "Enabling a person to discover or learn something for themselves; a practical method not guaranteed to be optimal", examples: ["A heuristic approach to problem-solving.", "Heuristic teaching methods encourage exploration."], synonyms: ["exploratory", "empirical", "practical", "rule-of-thumb"], antonyms: ["algorithmic", "systematic", "proven"], etymology: "Greek 'heuriskein' meaning 'to find'", relatedWords: ["rule-of-thumb", "shortcut", "method"], collocations: ["heuristic approach", "heuristic method", "heuristic algorithm"] },
  { word: "recursive", partOfSpeech: "adjective", definition: "Characterized by repetition, especially of a procedure or process applied to the result of a previous application", examples: ["A recursive function calls itself.", "The pattern is recursive in nature."], synonyms: ["repeating", "iterative", "cyclic", "self-referential"], antonyms: ["non-recursive", "linear", "one-shot"], etymology: "Latin 'recurrere' meaning 'to run back'", relatedWords: ["iteration", "repetition", "loop"], collocations: ["recursive function", "recursive process", "recursive definition"] },
  { word: "interface", partOfSpeech: "noun", definition: "A point where two systems, subjects, organizations, etc. meet and interact", examples: ["The user interface is intuitive.", "The interface connects two devices."], synonyms: ["connection", "junction", "boundary", "UI"], antonyms: [], etymology: "Latin 'inter' (between) + 'facies' (face)", relatedWords: ["UI", "API", "connection"], collocations: ["user interface", "graphical interface", "interface design"] },
  { word: "syntax", partOfSpeech: "noun", definition: "The arrangement of words and phrases to create well-formed sentences; the structure of statements in a computer language", examples: ["Check the syntax of your code.", "Syntax errors prevent compilation."], synonyms: ["grammar", "structure", "form", "rules"], antonyms: [], etymology: "Greek 'suntaxis' from 'sun-' (together) + 'taxis' (arrangement)", relatedWords: ["grammar", "structure", "semantics"], collocations: ["syntax error", "syntax highlighting", "syntax rules"] },
  { word: "protocol", partOfSpeech: "noun", definition: "A set of rules governing the exchange or transmission of data between devices", examples: ["Follow the network protocol.", "Security protocols are essential."], synonyms: ["procedure", "rules", "guidelines", "convention"], antonyms: [], etymology: "Greek 'protokollon' meaning 'first sheet glued to a manuscript'", relatedWords: ["rules", "procedure", "standard"], collocations: ["network protocol", "security protocol", "protocol stack"] },
  { word: "debug", partOfSpeech: "verb", definition: "Identify and remove errors from computer hardware or software", examples: ["I need to debug this code.", "Debugging takes patience and skill."], synonyms: ["fix", "troubleshoot", "repair", "correct"], antonyms: ["break", "corrupt"], etymology: "From 'de-' + 'bug', origin from Grace Hopper finding a moth in a computer", relatedWords: ["fix", "troubleshoot", "test"], collocations: ["debug code", "debug mode", "debug tool"] },
  { word: "aurora", partOfSpeech: "noun", definition: "A natural electrical phenomenon characterized by the appearance of streamers of reddish or greenish light in the sky", examples: ["The aurora borealis lit up the Arctic sky.", "We watched the aurora dance across the heavens."], synonyms: ["northern lights", "polar lights", "dawn"], antonyms: [], etymology: "Latin 'aurora' meaning 'dawn'", relatedWords: ["borealis", "australis", "lights"], collocations: ["aurora borealis", "aurora australis", "watch the aurora"] },
  { word: "petrichor", partOfSpeech: "noun", definition: "A pleasant smell that frequently accompanies the first rain after a long period of warm, dry weather", examples: ["I love the scent of petrichor.", "Petrichor filled the air after the drought ended."], synonyms: ["rain smell", "earth scent"], antonyms: [], etymology: "Greek 'petra' (rock) + 'ichor' (fluid of the gods)", relatedWords: ["rain", "earth", "scent"], collocations: ["smell of petrichor", "scent of petrichor"] },
  { word: "tsunami", partOfSpeech: "noun", definition: "A long high sea wave caused by an earthquake, submarine landslide, or other disturbance", examples: ["The tsunami devastated coastal towns.", "Tsunami warnings were issued after the earthquake."], synonyms: ["tidal wave", "sea surge"], antonyms: [], etymology: "Japanese 'tsu' (harbor) + 'nami' (wave)", relatedWords: ["wave", "earthquake", "disaster"], collocations: ["tsunami warning", "tsunami wave", "tsunami relief"] },
  { word: "volcano", partOfSpeech: "noun", definition: "A mountain or hill having a crater or vent through which lava, rock fragments, hot vapor, and gas are erupted", examples: ["The volcano erupted violently.", "Mount Kilimanjaro is a dormant volcano."], synonyms: ["mountain", "crater"], antonyms: [], etymology: "Latin 'Vulcanus', Roman god of fire", relatedWords: ["lava", "magma", "eruption"], collocations: ["active volcano", "volcano eruption", "dormant volcano"] },
  { word: "prairie", partOfSpeech: "noun", definition: "A large open area of grassland, especially in North America", examples: ["The prairie stretched to the horizon.", "Prairie dogs live in underground burrows."], synonyms: ["grassland", "savanna", "meadow", "plain"], antonyms: ["forest", "jungle"], etymology: "Latin 'pratum' meaning 'meadow'", relatedWords: ["grassland", "plain", "steppe"], collocations: ["vast prairie", "prairie dog", "prairie grass"] },
  { word: "fjord", partOfSpeech: "noun", definition: "A long, narrow, deep inlet of the sea between high cliffs, as in Norway and Iceland", examples: ["The Norwegian fjords are breathtaking.", "Glaciers carved the fjords thousands of years ago."], synonyms: ["inlet", "channel", "sound", "loch"], antonyms: [], etymology: "Norwegian 'fjord'", relatedWords: ["inlet", "channel", "glacier"], collocations: ["Norwegian fjord", "deep fjord", "fjord cruise"] },
  { word: "canopy", partOfSpeech: "noun", definition: "The uppermost branches of the trees in a forest, forming a kind of roof", examples: ["The rainforest canopy teems with life.", "Birds nested in the canopy above."], synonyms: ["covering", "shade", "umbrella", "awning"], antonyms: [], etymology: "Greek 'konopeion' meaning 'bed with mosquito curtains'", relatedWords: ["cover", "roof", "shade"], collocations: ["forest canopy", "canopy layer", "canopy cover"] },
  { word: "monsoon", partOfSpeech: "noun", definition: "A seasonal prevailing wind in the region of South and Southeast Asia, bringing heavy rain", examples: ["The monsoon brings much-needed rain to the region.", "Monsoon season can cause flooding."], synonyms: ["rainy season", "wet season"], antonyms: ["dry season"], etymology: "Arabic 'mawsim' meaning 'season'", relatedWords: ["rain", "season", "storm"], collocations: ["monsoon season", "monsoon rains", "monsoon climate"] },
  { word: "glacier", partOfSpeech: "noun", definition: "A slowly moving mass or river of ice formed by the accumulation of snow", examples: ["Glaciers are melting due to climate change.", "The glacier carved the valley over millennia."], synonyms: ["ice sheet", "ice mass", "ice field"], antonyms: [], etymology: "French 'glacier' from 'glace' meaning 'ice'", relatedWords: ["ice", "snow", "arctic"], collocations: ["melting glacier", "glacier national park", "retreating glacier"] },
  { word: "empathy", partOfSpeech: "noun", definition: "The ability to understand and share the feelings of another", examples: ["Show empathy towards others.", "Empathy is essential for good leadership."], synonyms: ["compassion", "understanding", "sensitivity", "sympathy"], antonyms: ["apathy", "indifference", "coldness"], etymology: "Greek 'empatheia' from 'em-' (in) + 'pathos' (feeling)", relatedWords: ["compassion", "sympathy", "understanding"], collocations: ["show empathy", "feel empathy", "empathy for"] },
  { word: "camaraderie", partOfSpeech: "noun", definition: "Mutual trust and friendship among people who spend a lot of time together", examples: ["The team had great camaraderie.", "Camaraderie built up over the project."], synonyms: ["friendship", "companionship", "solidarity", "fellowship"], antonyms: ["hostility", "animosity"], etymology: "French 'camarade' meaning 'roommate, companion'", relatedWords: ["friendship", "solidarity", "bond"], collocations: ["spirit of camaraderie", "sense of camaraderie", "great camaraderie"] },
  { word: "rapport", partOfSpeech: "noun", definition: "A close and harmonious relationship in which the people concerned understand each other's feelings or ideas", examples: ["She built good rapport with clients.", "There's an instant rapport between them."], synonyms: ["bond", "connection", "relationship", "understanding"], antonyms: ["conflict", "disconnection"], etymology: "French 'rapporter' meaning 'to bring back'", relatedWords: ["bond", "connection", "harmony"], collocations: ["build rapport", "good rapport", "establish rapport"] },
  { word: "altruism", partOfSpeech: "noun", definition: "Disinterested and selfless concern for the well-being of others", examples: ["Her altruism inspired everyone around her.", "True altruism expects nothing in return."], synonyms: ["selflessness", "generosity", "humanitarianism", "benevolence"], antonyms: ["selfishness", "egoism"], etymology: "French 'altruisme' from Italian 'altrui' meaning 'of or to others'", relatedWords: ["selflessness", "generosity", "charity"], collocations: ["act of altruism", "pure altruism", "human altruism"] },
  { word: "mentor", partOfSpeech: "noun", definition: "An experienced and trusted adviser who guides a less experienced person", examples: ["He was my mentor throughout my career.", "Find a mentor in your field."], synonyms: ["adviser", "guide", "coach", "tutor"], antonyms: ["student", "mentee"], etymology: "From Mentor, character in Homer's Odyssey", relatedWords: ["adviser", "guide", "coach"], collocations: ["find a mentor", "mentor relationship", "career mentor"] },
  { word: "epoch", partOfSpeech: "noun", definition: "A period of time in history or a person's life, typically one marked by notable events", examples: ["The invention of the internet marked a new epoch.", "We live in a digital epoch."], synonyms: ["era", "age", "period", "time"], antonyms: [], etymology: "Greek 'epokhe' meaning 'pause, fixed point'", relatedWords: ["era", "age", "period"], collocations: ["new epoch", "epoch-making", "geological epoch"] },
  { word: "eon", partOfSpeech: "noun", definition: "An indefinite and very long period of time; a billion years in geology", examples: ["It felt like eons passed.", "Geological eons span billions of years."], synonyms: ["age", "eternity", "millennium", "aeon"], antonyms: ["moment", "instant"], etymology: "Greek 'aion' meaning 'age, lifetime'", relatedWords: ["era", "age", "infinity"], collocations: ["for eons", "eons ago", "geological eon"] },
  { word: "chronological", partOfSpeech: "adjective", definition: "Following the order in which they occurred in time", examples: ["Arrange the events in chronological order.", "A chronological account of history."], synonyms: ["sequential", "ordered", "historical", "consecutive"], antonyms: ["random", "unordered"], etymology: "Greek 'khronos' (time) + 'logos' (study)", relatedWords: ["sequential", "ordered", "timeline"], collocations: ["chronological order", "chronological sequence", "chronological age"] },
  { word: "simultaneous", partOfSpeech: "adjective", definition: "Occurring, operating, or done at the same time", examples: ["Simultaneous translation was provided.", "The explosions were simultaneous."], synonyms: ["concurrent", "parallel", "synchronous", "coincident"], antonyms: ["sequential", "consecutive", "separate"], etymology: "Latin 'simul' meaning 'at the same time'", relatedWords: ["concurrent", "parallel", "synchronous"], collocations: ["simultaneous occurrence", "simultaneously", "simultaneous equations"] },
  { word: "perpetual", partOfSpeech: "adjective", definition: "Never ending or changing; continuing forever", examples: ["Perpetual motion is impossible.", "The perpetual noise was annoying."], synonyms: ["eternal", "everlasting", "continuous", "permanent"], antonyms: ["temporary", "transient", "brief", "finite"], etymology: "Latin 'perpetuus' meaning 'continuous, universal'", relatedWords: ["eternal", "continuous", "endless"], collocations: ["perpetual motion", "perpetual calendar", "perpetual student"] },
  { word: "schadenfreude", partOfSpeech: "noun", definition: "Pleasure derived from another person's misfortune", examples: ["His schadenfreude was obvious when his rival failed.", "There's a hint of schadenfreude in her laugh."], synonyms: ["gloating", "malicious joy"], antonyms: ["empathy", "compassion"], etymology: "German 'Schaden' (harm) + 'Freude' (joy)", relatedWords: ["gloating", "spite"], collocations: ["feel schadenfreude", "guilty schadenfreude"] },
  { word: "sonder", partOfSpeech: "noun", definition: "The realization that each random passerby is living a life as vivid and complex as your own", examples: ["Sonder hit me as I watched the crowd.", "Traveling often brings a sense of sonder."], synonyms: ["epiphany", "realization", "awareness"], antonyms: [], etymology: "Coined by John Koenig in The Dictionary of Obscure Sorrows", relatedWords: ["epiphany", "realization", "empathy"], collocations: ["sense of sonder", "experience sonder", "moment of sonder"] },
  { word: "defenestrate", partOfSpeech: "verb", definition: "To throw someone out of a window; (informal) to remove from a position of authority", examples: ["The CEO was defenestrated by the board.", "Figuratively, they defenestrated the old policy."], synonyms: ["eject", "oust", "remove", "throw out"], antonyms: ["install", "promote", "appoint"], etymology: "Latin 'de-' (down from) + 'fenestra' (window)", relatedWords: ["eject", "remove", "oust"], collocations: ["defenestrate from", "political defenestration"] },
  { word: "palimpsest", partOfSpeech: "noun", definition: "A manuscript on which later writing has been superimposed on earlier writing; a thing with layers of meaning", examples: ["The city is a palimpsest of cultures.", "Archaeologists found a medieval palimpsest."], synonyms: ["layer", "overlay", "relic", "trace"], antonyms: [], etymology: "Greek 'palimpsestos' from 'palin' (again) + 'psen' (to rub smooth)", relatedWords: ["layer", "trace", "relic"], collocations: ["cultural palimpsest", "urban palimpsest"] },
  { word: "susurrus", partOfSpeech: "noun", definition: "Whispering, murmuring, or rustling sound", examples: ["The susurrus of leaves in the wind.", "A soft susurrus filled the quiet room."], synonyms: ["whisper", "murmur", "rustle", "murmuration"], antonyms: ["shout", "clamor", "roar"], etymology: "Latin 'susurrus' meaning 'hum, whisper'", relatedWords: ["whisper", "murmur", "rustle"], collocations: ["susurrus of leaves", "gentle susurrus", "soft susurrus"] },
  { word: "labyrinthine", partOfSpeech: "adjective", definition: "Like a labyrinth; irregular and twisting; extremely complex", examples: ["Labyrinthine corridors of the old palace.", "The plot was labyrinthine in complexity."], synonyms: ["maze-like", "complex", "intricate", "convoluted"], antonyms: ["simple", "straightforward", "direct"], etymology: "Greek 'labyrinthos' from the myth of the Minotaur's maze", relatedWords: ["complex", "maze", "intricate"], collocations: ["labyrinthine corridors", "labyrinthine complexity", "labyrinthine plot"] },
  { word: "halcyon", partOfSpeech: "adjective", definition: "Denoting a period of time in the past that was idylically happy and peaceful", examples: ["She recalled the halcyon days of her youth.", "A halcyon summer by the lake."], synonyms: ["idylic", "peaceful", "happy", "tranquil"], antonyms: ["troubled", "stormy", "turbulent"], etymology: "Greek 'alkyon' referring to the kingfisher bird, believed to calm the sea", relatedWords: ["peaceful", "golden", "happy"], collocations: ["halcyon days", "halcyon period", "halcyon years"] },
  { word: "limerence", partOfSpeech: "noun", definition: "The state of being infatuated or obsessed with another person, typically experienced involuntarily", examples: ["Her limerence faded as she got to know him better.", "Limerence can feel like love but is fundamentally different."], synonyms: ["infatuation", "obsession", "crush", "passion"], antonyms: ["indifference", "apathy"], etymology: "Coined by psychologist Dorothy Tennov in 1979", relatedWords: ["infatuation", "obsession", "attraction"], collocations: ["state of limerence", "feel limerence", "limerence vs love"] },
  { word: "meraki", partOfSpeech: "noun", definition: "To do something with soul, creativity, or love; to put something of yourself into your work", examples: ["She cooked with meraki.", "This artwork was made with pure meraki."], synonyms: ["passion", "dedication", "soul", "love"], antonyms: ["apathy", "indifference"], etymology: "Greek 'meraki' meaning to do something with wholehearted devotion", relatedWords: ["passion", "soul", "devotion"], collocations: ["with meraki", "full of meraki", "do with meraki"] },
  { word: "kairos", partOfSpeech: "noun", definition: "The right, critical, or opportune moment; qualitative time as opposed to chronological time", examples: ["The speaker seized the kairos and changed minds.", "In kairos, timing is everything."], synonyms: ["opportunity", "moment", "occasion", "right time"], antonyms: [], etymology: "Greek 'kairos' meaning 'the right moment'", relatedWords: ["opportunity", "moment", "timing"], collocations: ["seize the kairos", "moment of kairos"] },
  { word: "saudade", partOfSpeech: "noun", definition: "A deep emotional state of nostalgic longing for something or someone that one loves but is absent", examples: ["She felt saudade for her hometown.", "The song evoked a sense of saudade."], synonyms: ["longing", "nostalgia", "yearning", "melancholy"], antonyms: [], etymology: "Portuguese 'saudade', with no direct English equivalent", relatedWords: ["nostalgia", "longing", "yearning"], collocations: ["feel saudade", "sense of saudade"] },
];

class Dictionary {
  private words: Map<string, DictionaryEntry> = new Map();
  private byPos: Map<string, DictionaryEntry[]> = new Map();

  constructor() {
    for (const entry of WORD_DATA) {
      this.words.set(entry.word.toLowerCase(), entry);
      const posList = this.byPos.get(entry.partOfSpeech) || [];
      posList.push(entry);
      this.byPos.set(entry.partOfSpeech, posList);
    }
  }

  lookup(word: string): DictionaryEntry | undefined {
    return this.words.get(word.toLowerCase().trim());
  }

  search(query: string): DictionaryEntry[] {
    const q = query.toLowerCase().trim();
    if (!q) return [];
    const exact = this.words.get(q);
    if (exact) return [exact];
    const results: DictionaryEntry[] = [];
    for (const [word, entry] of this.words) {
      if (word.includes(q) || entry.definition.toLowerCase().includes(q)) results.push(entry);
    }
    return results.slice(0, 10);
  }

  randomWord(): DictionaryEntry {
    const entries = Array.from(this.words.values());
    return entries[Math.floor(Math.random() * entries.length)];
  }

  get count(): number { return this.words.size; }
  getWordsByPos(pos: string): DictionaryEntry[] { return this.byPos.get(pos) || []; }
}

export const dictionary = new Dictionary();
